# Generated by Django 4.2.1 on 2023-06-16 16:08

from django.db import migrations

from compliance.models import AutomatedRequirementType


def seed_db(apps, schema_editor):
    Certificate = apps.get_model("compliance", "Certificate")
    Category = apps.get_model("compliance", "Category")
    Requirement = apps.get_model("compliance", "Requirement")

    # Create certificates
    comprehensive_baseline, created = Certificate.objects.get_or_create(
        name="Comprehensive Baseline",
        description="Verify that a business' cybersecurity measures and practices align with societal expectations and requirements",
    )
    cost_aware_baseline, created = Certificate.objects.get_or_create(
        name="Cost-Aware Baseline",
        description="Verify that a business has analyzed its cybersecurity risks and made informed decisions about which security measures to deploy in accordance with its budget",
        next_certificate=comprehensive_baseline,
    )
    technical_baseline, created = Certificate.objects.get_or_create(
        name="Technical Baseline",
        description="Verify that a business has basic cybersecurity measures and practices in place",
        next_certificate=cost_aware_baseline,
    )

    # Create categories
    asset_management, created = Category.objects.get_or_create(
        name="Asset Management",
        description="Verify that assets are identified and properly managed",
        certificate=technical_baseline,
    )
    protect, created = Category.objects.get_or_create(
        name="Protect",
        description="Verify that suitable security measures are implemented to safeguard the assets of a buisness",
        certificate=technical_baseline,
    )
    detect, created = Category.objects.get_or_create(
        name="Detect",
        description="Verify that there are activities and processes in place that help detecting cybersecurity incidents",
        certificate=technical_baseline,
    )
    respond, created = Category.objects.get_or_create(
        name="Respond",
        description="Verify that there are activities and processes in place to respond and mitigate detected cybersecurity incidents",
        certificate=technical_baseline,
    )
    recover, created = Category.objects.get_or_create(
        name="Recover",
        description="Verify that there are activities and processes in place to respond and mitigate detected cybersecurity incidents",
        certificate=technical_baseline,
    )

    risk_management, created = Category.objects.get_or_create(
        name="Risk Management",
        description="Verify that a business has the ability to analyze its cybersecurity risks and make informed decisions",
        certificate=cost_aware_baseline,
    )
    security_investments, created = Category.objects.get_or_create(
        name="Security Investments",
        description="Verify that a business has made a cost-benefit analysis to select its protections",
        certificate=cost_aware_baseline,
    )

    privacy_and_data_protection, created = Category.objects.get_or_create(
        name="Privacy and Data Protection",
        description="Verify that a business respects the rights and interests of its stakeholders when processing personal data",
        certificate=comprehensive_baseline,
    )
    training_and_awareness, created = Category.objects.get_or_create(
        name="Training and Awareness",
        description="Verify that a business cultivates a cybersecurity culture and provides cybersecurity threat awareness training to its employees",
        certificate=comprehensive_baseline,
    )
    collaboration_and_information_sharing, created = Category.objects.get_or_create(
        name="Collaboration and Information Sharing",
        description="Verify that a business contributes to the wider society by sharing relevant information about cybersecurity threats",
        certificate=comprehensive_baseline,
    )

    # Create technical requirements
    # Asset Management Requirements
    Requirement.objects.get_or_create(
        description="Do you know what information your business collects, processes and stores?",
        category=asset_management,
    )
    Requirement.objects.get_or_create(
        description="Do you maintain an up-to-date inventory that lists all your assets, such as data, IT systems and processes (software and hardware), external technologies (e.g., Cloud Services), and cybersecurity related responsibilities (e.g., reporting incidents and suspicious activities)?",
        category=asset_management,
    )
    Requirement.objects.get_or_create(
        description="Do you have a process for safe disposal of outdated computers or media such as CDs or USB drives?",
        category=asset_management,
    )

    # Protect Requirements
    Requirement.objects.get_or_create(
        description="Do you encrypt sensitive and confidential data at rest (i.e., stored on servers, databases, etc.)",
        category=protect,
    )
    Requirement.objects.get_or_create(
        description="Do you encrypt sensitive and confidential data in transit (i.e., during the transmission over the Internet)?",
        category=protect,
        is_automated_requirement=True,
        automated_requirement_type=AutomatedRequirementType.HTTPS_PROTOCOL_CHECKER
    )
    Requirement.objects.get_or_create(
        description="Is your network protected against unauthorized access from external sources by using e.g., firewalls or routers?",
        category=protect,
        is_automated_requirement=True,
        automated_requirement_type=AutomatedRequirementType.UNAUTHORIZED_ACCESS_CHECKER
    )
    Requirement.objects.get_or_create(
        description="Do you use multi-factor authentication (MFA) in addition to secure passwords whenever possible?",
        category=protect,
    )
    Requirement.objects.get_or_create(
        description="Do you ensure that all IT systems are securely configured (e.g., remove unnecessary user accounts, change default passwords, use of authentication to access data or services, etc.)?",
        category=protect,
    )
    Requirement.objects.get_or_create(
        description="Do you perform periodic security updates on all your IT systems and applications?",
        category=protect,
        is_automated_requirement=True,
        automated_requirement_type=AutomatedRequirementType.VULNERABILITY_CHECKER
    )

    # Detect Requirements
    Requirement.objects.get_or_create(
        description="Do you actively monitor your IT systems for malware (e.g., by utilizing up-to-date anti-virus, anti-spyware, or anti-malware software)?",
        category=detect,
    )
    Requirement.objects.get_or_create(
        description="Is the use of IT systems logged and are these logs maintained and monitored to make security incidents traceable?",
        category=detect,
    )
    Requirement.objects.get_or_create(
        description="Do you regularly monitor your network traffic and system logs for unusual or suspicious traffic (using e.g., IPS/IDS, SIEM, etc.)?",
        category=detect,
    )
    Requirement.objects.get_or_create(
        description="Have you established procedures for reporting security incidents and suspicious activities?",
        category=detect,
    )

    # Respond Requirements
    Requirement.objects.get_or_create(
        description="Do you have a documented response plan in place for security incidents such as system failure, malware attack or data leakage?",
        category=respond,
    )
    Requirement.objects.get_or_create(
        description="Do all employees know who is the contact point for reporting incidents?",
        category=respond,
    )
    Requirement.objects.get_or_create(
        description="Are employees aware of the appropriate ways for reporting potential security incidents?",
        category=respond,
    )
    Requirement.objects.get_or_create(
        description="Have you identified who is responsible for conducting security incident investigations and applying appropriate remediation?(e.g., trained personnel, contracted company, cyber insurance, etc.)",
        category=respond,
    )
    Requirement.objects.get_or_create(
        description="Do you update your incident response plan based on lessons learned from past incidents?",
        category=respond,
    )

    # Recover Requirements
    Requirement.objects.get_or_create(
        description="Do you have in-house knowledge to resume operations after a cyberattack or disaster?",
        category=recover,
    )
    Requirement.objects.get_or_create(
        description="Do you perform regular backups for your critical business information?",
        category=recover,
    )
    Requirement.objects.get_or_create(
        description="Do you keep backups outside the business environment in a protected location?",
        category=recover,
    )
    Requirement.objects.get_or_create(
        description="Do you encrypt your backups?", category=recover
    )
    Requirement.objects.get_or_create(
        description="Do regularly check whether data can be fully restored from your backups?",
        category=recover,
    )

    # Create economic requirements
    # Risk Management Requirements
    Requirement.objects.get_or_create(
        description="Have you determined the value of all assets, including information, software and hardware, that your businesses relies on?",
        category=risk_management,
    )
    Requirement.objects.get_or_create(
        description="Do you have a continuous process in place to identify and evaluate threats and vulnerabilites, and estimate the likelihood of them being exploited?",
        category=risk_management,
    )
    Requirement.objects.get_or_create(
        description="Have you prioritized the identified risks based on criticality?",
        category=risk_management,
    )
    Requirement.objects.get_or_create(
        description="Do you review your identified risks annually and whenever there is a change that can impact the risks?",
        category=risk_management,
    )

    # Security Investments Requirements
    Requirement.objects.get_or_create(
        description="Have you allocated a dedicated budget for cybersecurity investments in your company?",
        category=security_investments,
    )
    Requirement.objects.get_or_create(
        description="Are your cybersecurity investments allocated in a manner that balances the cost of risk mitigation with the potential financial impact of cybersecurity incidents (e.g., using Gordon-Loeb model)",
        category=security_investments,
    )
    Requirement.objects.get_or_create(
        description="Do you use metrics (e.g., ROSI) to compare potential cybersecurity solutions and prioritize the implementation of the more cost-efficient ones?",
        category=security_investments,
    )
    Requirement.objects.get_or_create(
        description="Have you considered investing in cyber insurance to mitigate potential financial impacts of security incidents?",
        category=security_investments,
    )

    # Create societal requirements
    # Privacy and Data Protection Requirements
    Requirement.objects.get_or_create(
        description="Do you have clear and up-to-date data protection policies that align with relevant data regulations (e.g., GDPR)?",
        category=privacy_and_data_protection,
    )
    Requirement.objects.get_or_create(
        description="Do you provide individuals with clear, concise, and easy-to-understand privacy notices that explain how their information is collected, used, and shared?",
        category=privacy_and_data_protection,
    )
    Requirement.objects.get_or_create(
        description="Do you collect, process, and store only the minimum amount of personal data necessary for your business operations?",
        category=privacy_and_data_protection,
    )
    Requirement.objects.get_or_create(
        description="Do you securely delete or anonymize personal data when it is no longer required for business purposes?",
        category=privacy_and_data_protection,
    )
    Requirement.objects.get_or_create(
        description="Do you have security controls in place that adequately protects personal information?",
        category=privacy_and_data_protection,
    )

    # Training and Awareness Requirements
    Requirement.objects.get_or_create(
        description="Do you provide regular security training and awareness programs for all employees that covers topics such as Phishing, Social Engineering and Password Management?",
        category=training_and_awareness,
    )
    Requirement.objects.get_or_create(
        description="Do you regularly update and improve security training to ensure employees remain aware of the latest threats and best practices?",
        category=training_and_awareness,
    )
    Requirement.objects.get_or_create(
        description="Do you encourage employees to report potential security issues or incidents, therefore actively promoting a culture of security awareness?",
        category=training_and_awareness,
    )

    # Collaboration and Information Sharing Requirements
    Requirement.objects.get_or_create(
        description="Do you report and share information about security incidents or vulnerabilities with relevant external parties such as authorities or partners?",
        category=collaboration_and_information_sharing,
    )
    Requirement.objects.get_or_create(
        description="Do you have rules in place about what cybersecurity information can be shared and who it can be shared with?",
        category=collaboration_and_information_sharing,
    )
    Requirement.objects.get_or_create(
        description="Have you joined any local or industry groups that share cybersecurity updates and warnings?",
        category=collaboration_and_information_sharing,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("compliance", "0001_initial"),
    ]

    operations = [migrations.RunPython(seed_db)]
